In [ ]:
import pandas as pd
import os

directory           = 'data'
classroom_file      = 'classrooms.csv'
instructor_file     = 'instructors.csv'
course_file         = 'courses.csv'
student_file        = 'students.csv'
timeslot_file       = 'timeslots.csv'

In [ ]:
classroom_df = pd.read_csv(os.path.join(directory, classroom_file))
course_df = pd.read_csv(os.path.join(directory, course_file))
instructor_df = pd.read_csv(os.path.join(directory, instructor_file))
student_df = pd.read_csv(os.path.join(directory, student_file))

In [ ]:
timeslot_df = pd.read_csv(os.path.join(directory, timeslot_file))
display(timeslot_df.head())

   timeslot_id        day start_time end_time
0            1  Wednesday      15:00    19:00
1            2     Friday      13:00    12:00
2            3   Thursday      13:00    17:00
3            4     Monday      16:00    15:00
4            5     Friday      10:00    11:00

In [ ]:
# Analyze classroom table
#------------------------

display(classroom_df.head())
classroom_check_null = classroom_df.isnull().sum()
if any(classroom_check_null > 0):
    print(classroom_check_null)

n_building = classroom_df.building_name.nunique()
building_room = (
    classroom_df
    .groupby('building_name', as_index=False)
    .agg(
        number_of_rooms = ('classroom_id', 'nunique'), 
        room_type = ('room_type', lambda x: x.unique().tolist()), 
        capacity = ('capacity', lambda x: x.unique().tolist())
    )
)
print(f"Number of buildings: {n_building}")
print(f"Room categories: {classroom_df.room_type.unique().tolist()}")
print(f"Room capacities: {sorted(classroom_df.capacity.unique().tolist())}")
display(building_room)

   classroom_id building_name  room_number  capacity     room_type
0             1             A          305        35  Lecture Hall
1             2             K          144        24     Classroom
2             3             B          710        46     Classroom
3             4             A          541        30     Classroom
4             5             I          747        35  Lecture Hall

Number of buildings: 12
Room categories: ['Lecture Hall', 'Classroom', 'Lab']
Room capacities: [21, 22, 23, 24, 25, 26, 27, 29, 30, 35, 36, 37, 38, 40, 41, 42, 43, 44, 45, 46]

,building_name,number_of_rooms,room_type,capacity
0,A,4,"[Lecture Hall, Classroom, Lab]","[35, 30, 21, 44]"
1,B,2,"[Classroom, Lecture Hall]","[46, 41]"
2,C,2,[Lab],"[37, 24]"
3,D,3,"[Lab, Lecture Hall]","[24, 29, 36]"
4,E,6,"[Lecture Hall, Classroom, Lab]","[29, 40, 36, 26, 30, 25]"
5,F,3,[Classroom],"[43, 27, 45]"
6,G,2,[Classroom],"[42, 24]"
7,H,1,[Lab],[23]
8,I,1,[Lecture Hall],[35]
9,J,1,[Lab],[44]
10,K,2,[Classroom],"[24, 46]"
11,L,3,[Lab],"[38, 22]"

In [ ]:
# Analyze course table
#---------------------

display(course_df.head())
course_check_null = course_df.isnull().sum()
if any(course_check_null > 0):
    print(course_check_null)

n_course = course_df.course_name.nunique()
department_course = (
    course_df
    .groupby('department', as_index=False)
    .agg(
        number_of_courses = ('course_name', 'nunique'), 
        credits = ('credits', lambda x: x.unique().tolist()), 
    )
)
print(f"Number of courses: {n_course}")
print(f"Number of departments: {course_df.department.nunique()}")
print(f"Credit categories: {sorted(course_df.credits.unique().tolist())}")
display(department_course)

,course_id,course_name,department,credits,description
0,1,Expanded web-enabled core,Chemistry,2,Approach themselves crime ground final which a...
1,2,Cross-group tertiary algorithm,Mechanical Engineering,1,Do player light black system instead. Everythi...
2,3,Synergized secondary throughput,Healthcare Informatics,1,Official seek candidate toward really. Throw s...
3,4,Object-based impactful groupware,Mathematics,3,Suddenly concern report choice benefit behavio...
4,5,Visionary leadingedge alliance,Engineering,4,Game grow catch bill. Now know evidence be foo...

Number of courses: 22
Number of departments: 10
Credit categories: [1, 2, 3, 4]

                department  number_of_courses    credits
0  Business Administration                  2        [3]
1                Chemistry                  5  [2, 3, 1]
2         Computer Science                  2     [3, 2]
3              Engineering                  1        [4]
4   Healthcare Informatics                  4  [1, 4, 2]
5               Management                  1        [3]
6              Mathematics                  1        [3]
7   Mechanical Engineering                  2     [1, 3]
8         Media Technology                  2     [3, 2]
9                  Physics                  2        [3]

In [ ]:
course_df.loc[0, 'description']

'Approach themselves crime ground final which after. Build pressure pick small north. Thing check weight none right quality major. Environment any picture leg already.'

In [ ]:
# Analyze instructor table
#-------------------------

display(instructor_df.head())
instructor_check_null = instructor_df.isnull().sum()
if any(instructor_check_null > 0):
    print(instructor_check_null)

n_instructor = instructor_df.instructor_id.nunique()
department_instructor = (
    instructor_df
    .groupby('department', as_index=False)
    .agg(
        number_of_instructors = ('instructor_id', 'nunique'), 
    )
)
print(f"Number of instructors: {n_instructor}")
display(department_instructor)

,instructor_id,first_name,last_name,email,phone_number,department
0,6ddac491-3bfa-420a-8098-f3c741f530b6,Danielle,Ponce,franklinchristopher@example.com,001-743-685-3222x9293,Computer Science
1,c3453dc3-772c-4d3b-b535-e058788237ed,Kenneth,Bradley,mitchell74@example.org,459.632.4543x037,Mathematics
2,55a493f1-a88a-4fe2-b666-b93388223926,William,Gamble,htorres@example.org,219.812.8147,Media Technology
3,8eb8ab26-579c-4927-8866-9f0cfb37824a,Willie,Ruiz,diane60@example.net,808-846-2697,Healthcare Informatics
4,7ceb34df-c5cd-4a6d-bbbd-ba393535b9d2,Shawn,Potts,lori31@example.org,+1-493-526-3451x7250,Chemistry

Number of instructors: 50

                department  number_of_instructors
0  Business Administration                      7
1                Chemistry                      6
2         Computer Science                      5
3              Engineering                      4
4   Healthcare Informatics                      6
5               Management                      7
6              Mathematics                      7
7   Mechanical Engineering                      1
8         Media Technology                      3
9                  Physics                      4

In [ ]:
# Analyze students
#-----------------

display(student_df.head())
student_check_null = student_df.isnull().sum()
if any(student_check_null > 0):
    print(student_check_null)

n_student = student_df.student_id.nunique()
n_program = student_df.program_name.nunique()

print(f"Number of students: {n_student}")
print(f"Number of programs: {n_program}")

,student_id,first_name,last_name,email,phone_number,address,program_name,year
0,2facd9b7-5ed9-4e51-90bd-629e3f4286d1,Scott,Mckenzie,vmata@example.com,+1-824-470-3964x7648,"925 Adams Freeway\nMooreville, SD 82191",M.Sc. in International Management,Sophomore
1,742bfaf3-68e9-4b41-85f3-1685751eda90,Anthony,Phillips,michaelsmith@example.org,+1-591-515-4305x63575,"0996 Ware Station\nAdamsview, AS 06846",M.Sc. in International Management,Junior
2,6b97e0b2-327d-4b55-84b7-b77c517fc087,Kimberly,Zimmerman,jeff57@example.net,(778)497-5565,"PSC 6308, Box 0623\nAPO AP 31497",M.Sc. in Mechatronics,Junior
3,f88fe06a-26db-48b2-8096-66e000259bbf,Austin,King,scott31@example.com,3163177631,"99932 Harris Dam\nDavismouth, HI 24660",M.Sc. in Applied Computer Science,Sophomore
4,e8bf1aee-c82e-422f-b7dc-8a3cf7d1ec2b,Renee,Bernard,obender@example.org,(465)613-1259x069,9156 Carpenter Skyway Apt. 161\nMichaelchester...,B.A. in Business Informatics,Junior

Number of students: 3000
Number of programs: 22

In [ ]:
display(
    student_df
    .groupby('program_name', as_index=False)
    .agg(year=('year', lambda x: x.unique().tolist()))
)

,program_name,year
0,B.A. in Business Informatics,"[Junior, Senior, Freshman, Sophomore]"
1,B.A. in International Management,"[Senior, Sophomore, Junior, Freshman]"
2,B.Eng. in Electrical Engineering,"[Freshman, Sophomore, Junior, Senior]"
3,B.Eng. in Mechatronics,"[Junior, Freshman, Senior, Sophomore]"
4,B.Sc. in Applied Computer Science,"[Senior, Sophomore, Junior, Freshman]"
5,B.Sc. in Applied Mathematics,"[Sophomore, Freshman, Junior, Senior]"
6,B.Sc. in Applied Physics,"[Senior, Junior, Freshman, Sophomore]"
7,B.Sc. in Artificial Intelligence,"[Senior, Junior, Sophomore, Freshman]"
8,B.Sc. in Healthcare Informatics,"[Senior, Freshman, Sophomore, Junior]"
9,B.Sc. in Media Technology and Design,"[Sophomore, Junior, Senior, Freshman]"
10,M.Sc. in Applied Chemistry and Environmental E...,"[Junior, Sophomore, Senior, Freshman]"
11,M.Sc. in Applied Computer Science,"[Sophomore, Senior, Freshman, Junior]"
12,M.Sc. in Applied Mathematics,"[Sophomore, Freshman, Junior, Senior]"
13,M.Sc. in Applied Physics,"[Senior, Junior, Freshman, Sophomore]"
14,M.Sc. in Business Informatics,"[Freshman, Junior, Senior, Sophomore]"
15,M.Sc. in Electrical Engineering and Informatio...,"[Junior, Freshman, Sophomore, Senior]"
16,M.Sc. in Healthcare Informatics,"[Sophomore, Junior, Freshman, Senior]"
17,M.Sc. in International Management,"[Sophomore, Junior, Senior, Freshman]"
18,M.Sc. in Mechanical Engineering,"[Junior, Freshman, Senior, Sophomore]"
19,M.Sc. in Mechatronics,"[Junior, Senior, Sophomore, Freshman]"
20,M.Sc. in Media Technology and Design,"[Senior, Sophomore, Freshman, Junior]"
21,M.Sc. in Technology and Management,"[Junior, Sophomore, Senior, Freshman]"